-- AlterTable
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "depositPaymentEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "fullPaymentEnabled" BOOLEAN NOT NULL DEFAULT true;
