-- AlterTable
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "roundTripDiscountPercent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "stripeEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "paypalEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "cashOnArrivalEnabled" BOOLEAN NOT NULL DEFAULT false;
