import type {
  AdminUser,
  Booking,
  BookingStatus,
  Driver,
  PricingRule,
  Settings,
  Zone,
} from "@/lib/types"

// In-memory demo store. Persists for the lifetime of the dev server process.
// In production these reads/writes would hit the real database.

const CURRENCY = "EUR"

function iso(offsetMinutes: number): string {
  return new Date(Date.now() + offsetMinutes * 60_000).toISOString()
}

const ORDER: BookingStatus[] = [
  "pending",
  "confirmed",
  "driver_assigned",
  "driver_accepted",
  "en_route",
  "arrived",
  "in_progress",
  "completed",
]

function buildTimeline(status: BookingStatus, pickupOffsetMin: number) {
  if (status === "cancelled") {
    return [
      { status: "pending" as BookingStatus, timestamp: iso(-2880) },
      { status: "confirmed" as BookingStatus, timestamp: iso(-2820) },
      { status: "cancelled" as BookingStatus, timestamp: iso(-1440) },
    ]
  }
  const reached = ORDER.slice(0, ORDER.indexOf(status) + 1)
  return reached.map((s, i) => ({
    status: s,
    timestamp: iso(pickupOffsetMin - (reached.length - i) * 45),
  }))
}

const drivers: Driver[] = [
  {
    id: "drv_01",
    name: "Marco Rossi",
    phone: "+39 320 111 2233",
    whatsappNumber: "+39 320 111 2233",
    vehicleMake: "Mercedes-Benz",
    vehicleModel: "E-Class",
    plateNumber: "MI 442 KJ",
    languages: ["Italian", "English"],
    vetted: true,
    active: true,
    avgRating: 4.9,
    pinSet: true,
  },
  {
    id: "drv_02",
    name: "Elena Bianchi",
    phone: "+39 331 998 7766",
    whatsappNumber: "+39 331 998 7766",
    vehicleMake: "BMW",
    vehicleModel: "5 Series",
    plateNumber: "RM 118 TP",
    languages: ["Italian", "English", "Spanish"],
    vetted: true,
    active: true,
    avgRating: 4.7,
    pinSet: true,
  },
  {
    id: "drv_03",
    name: "Youssef Haddad",
    phone: "+39 340 222 8899",
    whatsappNumber: "+39 340 222 8899",
    vehicleMake: "Volkswagen",
    vehicleModel: "Multivan",
    plateNumber: "NA 507 QR",
    languages: ["Italian", "English", "Arabic", "French"],
    vetted: true,
    active: true,
    avgRating: 4.8,
    pinSet: false,
  },
  {
    id: "drv_04",
    name: "Sofia Greco",
    phone: "+39 366 445 1122",
    whatsappNumber: "+39 366 445 1122",
    vehicleMake: "Audi",
    vehicleModel: "Q7",
    plateNumber: "TO 903 LM",
    languages: ["Italian", "German"],
    vetted: false,
    active: false,
    avgRating: 4.2,
    pinSet: false,
  },
  {
    id: "drv_05",
    name: "Luca Moretti",
    phone: "+39 388 776 3311",
    whatsappNumber: "+39 388 776 3311",
    vehicleMake: "Mercedes-Benz",
    vehicleModel: "V-Class",
    plateNumber: "BO 224 XY",
    languages: ["Italian", "English"],
    vetted: true,
    active: true,
    avgRating: 4.6,
    pinSet: true,
  },
]

const zones: Zone[] = [
  { id: "zone_01", name: "City Center" },
  { id: "zone_02", name: "Airport District" },
  { id: "zone_03", name: "Northern Suburbs" },
  { id: "zone_04", name: "Lakeside" },
]

const pricingRules: PricingRule[] = [
  { id: "pr_01", zoneId: "zone_01", zoneName: "City Center", vehicleType: "sedan", baseFare: 25, perKmRate: 1.8, minFare: 40, currency: CURRENCY },
  { id: "pr_02", zoneId: "zone_01", zoneName: "City Center", vehicleType: "premium", baseFare: 35, perKmRate: 2.2, minFare: 55, currency: CURRENCY },
  { id: "pr_03", zoneId: "zone_01", zoneName: "City Center", vehicleType: "minivan", baseFare: 45, perKmRate: 2.6, minFare: 70, currency: CURRENCY },
  { id: "pr_04", zoneId: "zone_02", zoneName: "Airport District", vehicleType: "sedan", baseFare: 20, perKmRate: 1.6, minFare: 35, currency: CURRENCY },
  { id: "pr_05", zoneId: "zone_02", zoneName: "Airport District", vehicleType: "minivan", baseFare: 40, perKmRate: 2.4, minFare: 65, currency: CURRENCY },
  { id: "pr_06", zoneId: "zone_04", zoneName: "Lakeside", vehicleType: "premium", baseFare: 55, perKmRate: 2.8, minFare: 90, currency: CURRENCY },
]

function driverSnapshot(d: Driver) {
  return { name: d.name, phone: d.phone, plateNumber: d.plateNumber }
}

const bookings: Booking[] = [
  {
    id: "bk_1001",
    referenceCode: "TRF-8F3K2A",
    pickupPin: "481029",
    direction: "airport_to_dest",
    pickupAddress: "Malpensa Airport (MXP), Terminal 1",
    dropoffAddress: "Hotel Duomo, Via Torino 12, City Center",
    pickupDateTime: iso(90),
    flightNumber: "BA2592",
    flightStatus: "on_time",
    passengerCount: 2,
    luggageCount: 3,
    vehicleType: "sedan",
    totalPrice: 78,
    depositAmount: 23.4,
    depositPaid: 23.4,
    balanceDue: 54.6,
    isBalanceCharged: false,
    balanceChargedAt: null,
    balanceChargedBy: null,
    paymentStatus: "deposit_paid",
    status: "confirmed",
    customer: { name: "James Whitfield", email: "j.whitfield@example.com", phone: "+44 7700 900123" },
    driver: null,
    driverId: null,
    currency: CURRENCY,
    freeCancellationUntil: iso(30),
    cancelledAt: null,
    cancellationOutcome: null,
    timeline: buildTimeline("confirmed", 90),
    notes: "Passenger requested a child booster seat.",
  },
  {
    id: "bk_1002",
    referenceCode: "TRF-2M9QP1",
    pickupPin: "739184",
    direction: "dest_to_airport",
    pickupAddress: "Residence Aurora, Viale Certosa 45, Northern Suburbs",
    dropoffAddress: "Malpensa Airport (MXP), Terminal 2",
    pickupDateTime: iso(180),
    flightNumber: "LH1899",
    flightStatus: "delayed",
    passengerCount: 4,
    luggageCount: 5,
    vehicleType: "minivan",
    totalPrice: 120,
    depositAmount: 36,
    depositPaid: 36,
    balanceDue: 84,
    isBalanceCharged: false,
    balanceChargedAt: null,
    balanceChargedBy: null,
    paymentStatus: "deposit_paid",
    status: "driver_assigned",
    customer: { name: "Anna Kowalski", email: "anna.k@example.com", phone: "+48 512 345 678" },
    driver: driverSnapshot(drivers[2]),
    driverId: "drv_03",
    currency: CURRENCY,
    freeCancellationUntil: iso(-60),
    cancelledAt: null,
    cancellationOutcome: null,
    timeline: buildTimeline("driver_assigned", 180),
  },
  {
    id: "bk_1003",
    referenceCode: "TRF-7HH4RC",
    pickupPin: "562730",
    direction: "airport_to_dest",
    pickupAddress: "Linate Airport (LIN), Arrivals",
    dropoffAddress: "Villa Serena, Via del Lago 8, Lakeside",
    pickupDateTime: iso(-30),
    flightNumber: "AZ2045",
    flightStatus: "landed",
    passengerCount: 3,
    luggageCount: 4,
    vehicleType: "premium",
    totalPrice: 145,
    depositAmount: 43.5,
    depositPaid: 43.5,
    balanceDue: 101.5,
    isBalanceCharged: false,
    balanceChargedAt: null,
    balanceChargedBy: null,
    paymentStatus: "deposit_paid",
    status: "en_route",
    customer: { name: "Diego Fernández", email: "d.fernandez@example.com", phone: "+34 600 112 233" },
    driver: driverSnapshot(drivers[0]),
    driverId: "drv_01",
    currency: CURRENCY,
    freeCancellationUntil: iso(-1440),
    cancelledAt: null,
    cancellationOutcome: null,
    timeline: buildTimeline("en_route", -30),
  },
  {
    id: "bk_1004",
    referenceCode: "TRF-5KD0ZE",
    pickupPin: "918457",
    direction: "dest_to_airport",
    pickupAddress: "Grand Hotel Central, Piazza Roma 1, City Center",
    dropoffAddress: "Malpensa Airport (MXP), Terminal 1",
    pickupDateTime: iso(-2880),
    flightNumber: "AF1329",
    flightStatus: "landed",
    passengerCount: 1,
    luggageCount: 2,
    vehicleType: "sedan",
    totalPrice: 82,
    depositAmount: 24.6,
    depositPaid: 24.6,
    balanceDue: 57.4,
    isBalanceCharged: false,
    balanceChargedAt: null,
    balanceChargedBy: null,
    paymentStatus: "deposit_paid",
    status: "completed",
    customer: { name: "Priya Nair", email: "priya.nair@example.com", phone: "+91 98200 45678" },
    driver: driverSnapshot(drivers[1]),
    driverId: "drv_02",
    currency: CURRENCY,
    freeCancellationUntil: iso(-4320),
    cancelledAt: null,
    cancellationOutcome: null,
    timeline: buildTimeline("completed", -2880),
  },
  {
    id: "bk_1005",
    referenceCode: "TRF-9WP3LQ",
    pickupPin: "204861",
    direction: "airport_to_dest",
    pickupAddress: "Malpensa Airport (MXP), Terminal 1",
    dropoffAddress: "Corporate Tower, Via Melchiorre Gioia 22, City Center",
    pickupDateTime: iso(-4320),
    flightNumber: "KL1611",
    flightStatus: "landed",
    passengerCount: 2,
    luggageCount: 2,
    vehicleType: "premium",
    totalPrice: 96,
    depositAmount: 28.8,
    depositPaid: 28.8,
    balanceDue: 67.2,
    isBalanceCharged: true,
    balanceChargedAt: iso(-4320),
    balanceChargedBy: "admin",
    paymentStatus: "fully_paid",
    status: "completed",
    customer: { name: "Robert Chen", email: "r.chen@example.com", phone: "+1 415 555 0198" },
    driver: driverSnapshot(drivers[4]),
    driverId: "drv_05",
    currency: CURRENCY,
    freeCancellationUntil: iso(-5760),
    cancelledAt: null,
    cancellationOutcome: null,
    timeline: buildTimeline("completed", -4320),
  },
  {
    id: "bk_1006",
    referenceCode: "TRF-1AB6YT",
    pickupPin: "657392",
    direction: "dest_to_airport",
    pickupAddress: "Lakeview Apartments, Via Como 3, Lakeside",
    dropoffAddress: "Linate Airport (LIN), Departures",
    pickupDateTime: iso(150),
    flightNumber: "IB3251",
    flightStatus: "scheduled",
    passengerCount: 2,
    luggageCount: 2,
    vehicleType: "sedan",
    totalPrice: 88,
    depositAmount: 26.4,
    depositPaid: 26.4,
    balanceDue: 61.6,
    isBalanceCharged: false,
    balanceChargedAt: null,
    balanceChargedBy: null,
    paymentStatus: "deposit_paid",
    status: "pending",
    customer: { name: "Marie Dubois", email: "m.dubois@example.com", phone: "+33 6 12 34 56 78" },
    driver: null,
    driverId: null,
    currency: CURRENCY,
    freeCancellationUntil: iso(90),
    cancelledAt: null,
    cancellationOutcome: null,
    timeline: buildTimeline("pending", 150),
  },
  {
    id: "bk_1007",
    referenceCode: "TRF-4RT8NM",
    pickupPin: "813046",
    direction: "airport_to_dest",
    pickupAddress: "Malpensa Airport (MXP), Terminal 2",
    dropoffAddress: "Conference Center, Via Gattamelata 5, Northern Suburbs",
    pickupDateTime: iso(240),
    flightNumber: "UA0900",
    flightStatus: "on_time",
    passengerCount: 6,
    luggageCount: 8,
    vehicleType: "minivan",
    totalPrice: 175,
    depositAmount: 52.5,
    depositPaid: 52.5,
    balanceDue: 122.5,
    isBalanceCharged: false,
    balanceChargedAt: null,
    balanceChargedBy: null,
    paymentStatus: "deposit_paid",
    status: "pending",
    customer: { name: "Tomasz Nowak", email: "t.nowak@example.com", phone: "+48 601 234 567" },
    driver: null,
    driverId: null,
    currency: CURRENCY,
    freeCancellationUntil: iso(180),
    cancelledAt: null,
    cancellationOutcome: null,
    timeline: buildTimeline("pending", 240),
  },
  {
    id: "bk_1008",
    referenceCode: "TRF-6QC2WD",
    pickupPin: "375920",
    direction: "dest_to_airport",
    pickupAddress: "Hotel Bellavista, Via Manzoni 9, City Center",
    dropoffAddress: "Malpensa Airport (MXP), Terminal 1",
    pickupDateTime: iso(-1440),
    flightNumber: "EK0206",
    flightStatus: "cancelled",
    passengerCount: 2,
    luggageCount: 3,
    vehicleType: "premium",
    totalPrice: 110,
    depositAmount: 33,
    depositPaid: 33,
    balanceDue: 77,
    isBalanceCharged: false,
    balanceChargedAt: null,
    balanceChargedBy: null,
    paymentStatus: "refunded",
    status: "cancelled",
    customer: { name: "Olivia Brown", email: "o.brown@example.com", phone: "+61 400 123 456" },
    driver: null,
    driverId: null,
    currency: CURRENCY,
    freeCancellationUntil: iso(-1500),
    cancelledAt: iso(-1440),
    cancellationOutcome: "free_cancellation",
    timeline: buildTimeline("cancelled", -1440),
  },
  {
    id: "bk_1009",
    referenceCode: "TRF-3ZX5PL",
    pickupPin: "129684",
    direction: "airport_to_dest",
    pickupAddress: "Malpensa Airport (MXP), Terminal 1",
    dropoffAddress: "Business Bay Hotel, Via Vittor Pisani 14, City Center",
    pickupDateTime: iso(200),
    flightNumber: "QR0127",
    flightStatus: "on_time",
    passengerCount: 1,
    luggageCount: 1,
    vehicleType: "sedan",
    totalPrice: 74,
    depositAmount: 22.2,
    depositPaid: 22.2,
    balanceDue: 51.8,
    isBalanceCharged: false,
    balanceChargedAt: null,
    balanceChargedBy: null,
    paymentStatus: "deposit_paid",
    status: "confirmed",
    customer: { name: "Hiroshi Tanaka", email: "h.tanaka@example.com", phone: "+81 90 1234 5678" },
    driver: null,
    driverId: null,
    currency: CURRENCY,
    freeCancellationUntil: iso(140),
    cancelledAt: null,
    cancellationOutcome: null,
    timeline: buildTimeline("confirmed", 200),
  },
]

const settings: Settings = {
  companyName: "Transfer Ops",
  supportPhone: "+39 02 8901 2345",
  supportEmail: "ops@transfers.co",
  supportWhatsApp: "+39 320 000 1122",
  adminNotificationEmail: "ops@transfers.co",
  displayCurrencies: ["EUR", "GBP"],
  freeCancellationHours: 24,
  depositPercentage: 30,
  roundTripDiscountPercent: 0,
  infantCarrierPrice: 10,
  childSeatPrice: 12,
  boosterSeatPrice: 8,
  stripeEnabled: true,
  paypalEnabled: true,
  cashOnArrivalEnabled: false,
  depositPaymentEnabled: true,
  fullPaymentEnabled: true,
  airports: [
    { name: "Milan Malpensa", iataCode: "MXP" },
    { name: "Milan Linate", iataCode: "LIN" },
    { name: "Bergamo Orio al Serio", iataCode: "BGY" },
  ],
  notificationChannelsEnabled: {
    confirmation: true,
    driverAssigned: true,
    flightDelay: true,
    reminder: true,
    cancellation: false,
    dateChange: true,
    completedReceipt: true,
  },
  flightDelayThresholdMinutes: 45,
  whatsappConnectionStatus: "connected",
  stripeMode: "test",
  paypalMode: "live",
  stripeTestPublishableKey: "",
  stripeLivePublishableKey: "",
  stripeTestSecretKeySet: false,
  stripeLiveSecretKeySet: false,
  stripeTestWebhookSecretSet: false,
  stripeLiveWebhookSecretSet: false,
  paypalSandboxClientId: "",
  paypalLiveClientId: "",
  paypalSandboxSecretSet: false,
  paypalLiveSecretSet: false,
}

const adminUsers: AdminUser[] = [
  {
    id: "usr_01",
    name: "Ops Team",
    email: "ops@transfers.co",
    role: "admin",
    suspended: false,
    lastLoginAt: iso(-120),
    requiresPasswordReset: false,
  },
  {
    id: "usr_02",
    name: "Giulia Ferrari",
    email: "giulia@transfers.co",
    role: "operator",
    suspended: false,
    lastLoginAt: iso(-2880),
    requiresPasswordReset: false,
  },
  {
    id: "usr_03",
    name: "Daniel Osei",
    email: "daniel@transfers.co",
    role: "operator",
    suspended: false,
    lastLoginAt: null,
    requiresPasswordReset: true,
  },
]

export const store = {
  bookings,
  drivers,
  zones,
  pricingRules,
  settings,
  adminUsers,
  currency: CURRENCY,
}

let bookingSeq = 1010
let driverSeq = 6
let zoneSeq = 5
let ruleSeq = 7
let userSeq = 4

export function nextId(kind: "booking" | "driver" | "zone" | "rule" | "user") {
  switch (kind) {
    case "booking":
      return `bk_${bookingSeq++}`
    case "driver":
      return `drv_${String(driverSeq++).padStart(2, "0")}`
    case "zone":
      return `zone_${String(zoneSeq++).padStart(2, "0")}`
    case "rule":
      return `pr_${String(ruleSeq++).padStart(2, "0")}`
    case "user":
      return `usr_${String(userSeq++).padStart(2, "0")}`
  }
}

export { ORDER as STATUS_ORDER, driverSnapshot }
