-- AlterTable
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "smtpHost" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "smtpPort" INTEGER NOT NULL DEFAULT 465;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "smtpSecure" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "smtpUser" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "smtpPass" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "smtpFrom" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "smtpTlsRejectUnauthorized" BOOLEAN NOT NULL DEFAULT true;
